datahub:
  hubs:
    - id: "s3_preops"
      url: "https://scihub.copernicus.eu/s3"
      username: "s3guest"
      password: "s3guest"
#      parallelDownloads: 3
    - id: "dias"
      url: "https://catalogue.onda-dias.eu/dias-catalogue"
      username: "fernando.marino85@gmail.com"
      password: "password"
#      parallelDownloads: 5
    - id: "scihub"
      url: "https://scihub.copernicus.eu/dhus"
      username: "test"
      password: "test"
#      parallelDownloads: 5
    - id: "s5p"
      url: "https://s5phub.copernicus.eu/dhus"
      username: "s5pguest"
      password: "s5pguest"
  proxyUrl: "none"

geoserver:
  baseUrl: "http://51.38.225.223/geoserver/"
  username: "admin"
  password: "S3_supp0rt"
  workspace: "esb"

#debug: true